### ISSUE TITLE
Działania 1/x

### ISSUE THREAD

**Issue by haribo841** [Projekt-Inzynierski-AK-AS-FD/Projekt-Inzynierski#4]
Plik: Calculator.xaml.cs
Linijka: 723
if (!(elements[1].Contains('√') || elements[1].Contains('²')) && Convert.ToDouble(elements[1]) * 1 == 0)

Działanie x:(1/x) wywala program.

System.FormatException
  HResult=0x80131537
  Message=Input string was not in a correct format.
  Source=mscorlib
  StackTrace:
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ToDouble(String value)
   at Abituria.Calculator.SprawdzCzyNieZero(String operation) in C:\Users\Adam\source\repos\Abituria\Abituria szkielet\Calculator.xaml.cs:line 723
   at Abituria.Calculator.Button_ClickUlamek(Object sender, RoutedEventArgs e) in C:\Users\Adam\source\repos\Abituria\Abituria szkielet\Calculator.xaml.cs:line 592
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at Abituria.App.Main()

  This exception was originally thrown at this call stack:
    System.Number.ParseDouble(string, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
    System.Convert.ToDouble(string)
    Abituria.Calculator.SprawdzCzyNieZero(string) in Calculator.xaml.cs
    Abituria.Calculator.Button_ClickUlamek(object, System.Windows.RoutedEventArgs) in Calculator.xaml.cs
    System.Windows.RoutedEventHandlerInfo.InvokeHandler(object, System.Windows.RoutedEventArgs)
    System.Windows.EventRoute.InvokeHandlersImpl(object, System.Windows.RoutedEventArgs, bool)
    System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
    System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
    System.Windows.Controls.Primitives.ButtonBase.OnClick()
    System.Windows.Controls.Button.OnClick()
    ...
    [Call Stack Truncated]

**Comment by haribo841** [comment]
Dla ułatwienia nazwijmy naszą liczbę 'λ'. Działanie λ*(1/x) działa jak λ^2*(1/x)=(1/λ*λ).
Jak dla mnie coś takiego nie powinno w ogóle mieć miejsca. Przede wszystkim dlatego, że funkcję (1/x) traktujemy jako działanie i będzie to drugie w równaniu co jest błędne, gdyż działania (w tym działanie '*' -mnożenia) te są dwuargumentowe, a argumentem może być tylko liczba. Przyjęcie innego działania jako drugi argument liczbowy jest po prostu nie poprawne.
Normalnie spodziewalibyśmy się np. dla λ=9, gdzie (1/x)=⨍(λ), to po podstawieniu powinniśmy mieć ⨍(1/9).
![image](https://user-images.githubusercontent.com/48011447/144764032-dfc77253-0958-49c8-b65b-cde9f627435e.png)
Nie wiem jak to sobie wyobrażałeś i co miałeś w głowie pisząc to, bo mnie w głowie się nie mieści ( ´･･)ﾉ(._.`)
Oczywistym jest, że: 9*(1/9)=1,
![image](https://user-images.githubusercontent.com/48011447/144764267-f5bf67bf-55f3-46a7-af7b-ec88df67b16c.png)
![image](https://user-images.githubusercontent.com/48011447/144764280-d109b9b1-7c1c-4f04-9e90-25c1fd344df4.png)
 tylko że, dostajemy tutaj 1/81
![image](https://user-images.githubusercontent.com/48011447/144764097-594690ed-171c-4661-b684-88292a85f185.png)
Wątpię, że chodziło tu o składanie funkcji. Nie wiem skąd wziął się drugi argument liczbowy dający taki wynik, bo przecież (1/x) to nie jest 9. Mózg mi rapuje. 9*_(9)_=81→⨍(λ)→1/81. Nie jestem tego w stanie zrozumieć, also jak wykonasz działanie,
![image](https://user-images.githubusercontent.com/48011447/144764351-6ca007c9-2ab3-43fb-b4c0-4c5f56fa9506.png)
to wysypiesz kalkulator na linijce: 687.
```
					{❌
						if (!parseDecimal)
						{
							number.scale = 0;
						}
						if ((state & 0x10) == 0)
						{
							number.sign = false;
						}
					}
```
System.FormatException
  HResult=0x80131537
  Message=Input string was not in a correct format.
  Source=mscorlib
  StackTrace:
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt) in f:\dd\ndp\clr\src\BCL\system\number.cs:line 694
   at System.Convert.ToDouble(String value) in f:\dd\ndp\clr\src\BCL\system\convert.cs:line 1603
   at Abituria.Calculator.CalculateResult(String operation) in C:\Users\Filippo\source\repos\Kalkulator\Projekt-Inzynierski\Calculator.xaml.cs:line 1427
   at Abituria.Calculator.Button_ClickPotega(Object sender, RoutedEventArgs e) in C:\Users\Filippo\source\repos\Kalkulator\Projekt-Inzynierski\Calculator.xaml.cs:line 820
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Abituria.App.Main()

  This exception was originally thrown at this call stack:
    System.Number.ParseDouble(string, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo) in number.cs
    System.Convert.ToDouble(string) in convert.cs
    Abituria.Calculator.CalculateResult(string) in Calculator.xaml.cs
    Abituria.Calculator.Button_ClickPotega(object, System.Windows.RoutedEventArgs) in Calculator.xaml.cs
    System.Windows.EventRoute.InvokeHandlersImpl(object, System.Windows.RoutedEventArgs, bool)
    System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
    System.Windows.Controls.Primitives.ButtonBase.OnClick()
    System.Windows.Controls.Button.OnClick()
    System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(System.Windows.Input.MouseButtonEventArgs)
    System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, object)
    ...
    [Call Stack Truncated]

**Comment by haribo841** [comment]
Po poprawce bez zmian.
![image](https://user-images.githubusercontent.com/48011447/144850247-2215c28a-2bf2-43be-bca0-447847c316bb.png)

**Comment by Filippo1998r** [comment]
Okej, rozumiem ideę. Po prostu zdefiniowałem "liczbę1 i jakiś znak" (tutaj 9*) jako "liczba1 znak liczba1" (9*9), bo tak jest przy zakończeniu działania w Windows'ie, tak jak u mnie tylko widać niepoprawnie to wychodzi z zakończeniem po przez działanie 1/x. Już naprawiam. Bugiem też się zajmę ale najpierw to.

**Comment by Filippo1998r** [comment]
o a co do tego bugu na zdjęciu, skąd pan wziął kropkę?

**Comment by haribo841** [comment]
Angielski windows. Poprzez bug masz na myśli ten issue #4? U Billa wynik jest taki jak przy samym działaniu 1:9. Na telefonie funkcja (1/x) dopisuje zawsze '1:', więc działanie czeka na argument liczbowy: '9x1:'
![image](https://user-images.githubusercontent.com/48011447/144885422-42954a4b-e651-4e09-a87d-7bbb9cceffb4.png)

**Comment by Filippo1998r** [comment]
Konkretnie to co oznaczyłeś jako bug powyżej, tam gdzie się wysypywało. Zrobione jak u Billa

**Comment by astolowska** [comment]
![image](https://user-images.githubusercontent.com/48011791/145721516-633db281-2440-4875-9490-d0f9f922b887.png)
Po kręceniu wyników w kółko (działanie : a potem 1/x i tak ciągle) w końcu dostajemy takie cudo, jak pusty ekran działania.
