### ISSUE TITLE
return Convert.ToDouble(elements[0]) / Convert.ToDouble(elements[1]);

### ISSUE THREAD

**Issue by haribo841** [Projekt-Inzynierski-AK-AS-FD/Projekt-Inzynierski#8]
Plik: Calculator.xamsl.cs
Linijka: 1364
return Convert.ToDouble(elements[0]) / Convert.ToDouble(elements[1]);

Działanie (1/x), gdzie x=(1/y√z) wysypuje program.

System.FormatException
  HResult=0x80131537
  Message=Input string was not in a correct format.
  Source=mscorlib
  StackTrace:
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ToDouble(String value)
   at Abituria.Calculator.CalculateResult(String operation) in C:\Users\Adam\source\repos\Abituria\Abituria szkielet\Calculator.xaml.cs:line 1364
   at Abituria.Calculator.Button_ClickUlamek(Object sender, RoutedEventArgs e) in C:\Users\Adam\source\repos\Abituria\Abituria szkielet\Calculator.xaml.cs:line 596
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at Abituria.App.Main()

  This exception was originally thrown at this call stack:
    System.Number.ParseDouble(string, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
    System.Convert.ToDouble(string)
    Abituria.Calculator.CalculateResult(string) in Calculator.xaml.cs
    Abituria.Calculator.Button_ClickUlamek(object, System.Windows.RoutedEventArgs) in Calculator.xaml.cs
    System.Windows.RoutedEventHandlerInfo.InvokeHandler(object, System.Windows.RoutedEventArgs)
    System.Windows.EventRoute.InvokeHandlersImpl(object, System.Windows.RoutedEventArgs, bool)
    System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
    System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
    System.Windows.Controls.Primitives.ButtonBase.OnClick()
    System.Windows.Controls.Button.OnClick()
    ...
    [Call Stack Truncated]

**Comment by haribo841** [comment]
Podnoszenie liczb zmiennoprzecinkowych również wysypuje program, nieznikająca nawet po crashu historia to potwierdzi.
![image](https://user-images.githubusercontent.com/48011447/144519629-ffa80779-e208-436f-8b5e-6b8a9e410fee.png)

**Comment by haribo841** [comment]
Historia już znika po wysypaniu się programu, a podnoszenie rezultuje wysypaniem się z błędem takim jak w #4 
Historia daje wgląd tylko w pierwsze 21 działań i dostęp tylko do pierwszych 21 wyników. Samo równanie 21 jest ucięte, a dalej nic nie widać i nie można nic z tym zrobić. Zobacz również jakie otrzymałem wyniki działań. (╯°□°）╯︵ ┻━┻
![image](https://user-images.githubusercontent.com/48011447/144765352-a2d6c94a-cbac-40aa-afe5-8e00a26aafc2.png)

**Comment by haribo841** [comment]
Problem nadal istnieje. Czyszczenie historii jest jakimś rozwiązaniem.

**Comment by astolowska** [comment]
Po kolejnych aktualizacjach problem dalej nie ruszony. Konkatenacja trwa.
![image](https://user-images.githubusercontent.com/48011791/145720433-ef758bd2-3982-4630-a064-1b2aec07ef01.png)

**Comment by Filippo1998r** [comment]
Konkatenacja wydawała mi się tu bardziej intuicyjna po prostu, ale mogę to zmienić. Pytanie czy to miało by wyglądać na zasadzie: mam 1/15 klikam 4 i działanie zamienia się na 4?
